# Generated by Django 6.0.1 on 2026-03-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('GPU', 'GPU'), ('CPU', 'CPU'), ('RAM', 'RAM'), ('SSD', 'SSD')], max_length=20),
        ),
    ]
