# Generated by Django 6.0.1 on 2026-03-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='approval_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='rejection_seen',
            field=models.BooleanField(default=False),
        ),
    ]
